// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd1q52Ys5W0JlZhgx5BIG6UfQrjxebO2w',
    appId: '1:486169093218:web:39f7cb916516a1fbdd9d3b',
    messagingSenderId: '486169093218',
    projectId: 'riceapp-aafca',
    authDomain: 'riceapp-aafca.firebaseapp.com',
    storageBucket: 'riceapp-aafca.appspot.com',
    measurementId: 'G-S0QCJEH0WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_zOPFa26H2FyOGsNaBAqqJZ4ZSHu1Wd0',
    appId: '1:486169093218:android:25571086982d3d6add9d3b',
    messagingSenderId: '486169093218',
    projectId: 'riceapp-aafca',
    storageBucket: 'riceapp-aafca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgI1xK1SAig_Q-H_23pDn6OYVN4DsbJPU',
    appId: '1:486169093218:ios:300d4d4fc30fb3a8dd9d3b',
    messagingSenderId: '486169093218',
    projectId: 'riceapp-aafca',
    storageBucket: 'riceapp-aafca.appspot.com',
    iosBundleId: 'com.example.riceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgI1xK1SAig_Q-H_23pDn6OYVN4DsbJPU',
    appId: '1:486169093218:ios:446f567e7a96c1e4dd9d3b',
    messagingSenderId: '486169093218',
    projectId: 'riceapp-aafca',
    storageBucket: 'riceapp-aafca.appspot.com',
    iosBundleId: 'com.example.riceApp.RunnerTests',
  );
}
